<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBecNpMA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBecNpMA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBecNpMA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBecNpMA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBecNpMA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BecNpMA',
    'container.build_id' => 'c805c5ec',
    'container.build_time' => 1528119226,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBecNpMA');
